spring:
  datasource:
    url: jdbc:postgresql://ep-dry-sound-att0l00f-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Ok7zPG2IxjEp&sslmode=require&channelBinding=require
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_Ok7zPG2IxjEp}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.healthsync: INFO
    org.springframework: WARN
